name: E2E Test

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/actions/install-deps

      - name: Build extension
        run: |
          npm run build:libs
          npm run build:extension-chrome

      - name: E2E
        run: |
          npx playwright install
          xvfb-run --auto-servernum npm run e2e -- --testTimeout=20000
